feat: don't compute input source maps if source file hasn't changed
Khan/uglifyjs-webpack-plugin pull request #1
Opened 2019-01-15 22:04 UTC by kevinbarabash

This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

The plugin does a lot of work computing input source maps when it isn't necessary, i.e. the cache key hasn't changed and we already have a source map in our cache for the key.

### Breaking Changes

This shouldn't be a breaking change, but I'm not super familiar with all of the possible configurations for this plugin.

### Additional Info

This change looks a lot bigger than it actually is.  Because of the `cacache.get.info()` call that's introduced index, I had to wrap a big chunk of `optimizeFn` in a `Promise.all()` call because `cacache.get.info()` returns a promise and before this everything in `optimizeFn` was synchronous.

2019-01-15 22:06 UTC, kevinbarabash commented on src/index.js
> +                cacheKey = serialize(defaultCacheKeys);
We do the serialization of the cache keys once and pass that to the TaskRunner so we don't have to do it again.

2019-01-15 22:06 UTC, kevinbarabash commented on src/index.js
> -              const { source, map } = asset.sourceAndMap();
Apparently sourceAndMap is supposed to be faster than calling `asset.source()` and `asset.map()` separately, but not having to call `asset.map()` if we have the output source map cached is even faster. :)

2019-01-15 22:06 UTC, kevinbarabash commented on src/index.js
> -              task.cacheKeys = this.options.cacheKeys(defaultCacheKeys, file);
I moved the computation of the cache keep up so that we can check whether the key exists in the cache before computing the input source map.

2019-01-15 22:06 UTC, kevinbarabash commented on src/index.js
> +        taskRunner.run(tasks, (tasksError, results) => {
The callback to taskRunner is unchanged, I've only wrapped it in a .then() now that the computation of tasks is async.

2019-01-16 16:30 UTC, kevinbarabash commented
This PR needs fixing.  The build fails when there's a file that doesn't exist in the cache.  I'm surprised that the tests didn't cover this case.

2019-01-16 16:45 UTC, jeresig requested changes
To be really confident in this we need to up our test plan:

From a completely fresh build:

```
rm -rf genwebpack/prod
rm -rf genwebpack/.cache-loader
rm -rf node_modules/.cache/uglifyjs-webpack-plugin
time npm run build:webpack-prod-profile --no-i18n
find genwebpack/prod/en -type f -exec shasum "{}" ';' > checksums.txt
```

And then again to test the cached copy:

```
time npm run build:webpack-prod-profile --no-i18n
find genwebpack/prod/en -type f -exec shasum "{}" ';' > checksums.txt
```

How long does that take with and without your change? I'd save copies of the checksums.txt file for each run (without your change: uncached & cached, with your change: uncached & cached). Every single one of these files should be identical. You could run `diff -u checksums1.txt checksums2.txt` and there should be not output - you should do that for each file. Additionally each time you run those lines above (except for the first) I'd then run: `shasum -c checksums1.txt` to verify that all of the output files match your expectations.

So to clarify, you're running this 4 times (without your change: uncached & cached, with your change: uncached & cached) and for each run you should have:

- A timing of the run.
- A file of the checksums of all the files produced in genwebpack/prod/en
- A validation that the checksums file from the very first run (uncached without your changes) matches every other run (by doing a diff).
- A validation that the checksums match the output in genwebpack (by using shasum).

Update: Oh! Also we should verify that changing a file will actually still work and cause it to re-build correctly! So you should also test modifying a file and verifying that only the expected packages actually change.

2019-01-16 18:51 UTC, kevinbarabash commented
Copied from slack:
> I fixed the issue I was seeing with my UglifyJSPlugin changes and doing a fresh build.  There was some out of date code in the plugin’s dist/ folder.  Rebuilding the plugin fixed everything.  I’m going to be working on comparing the output with and without the changes and then benchmarking different build scenarios.

2019-01-16 20:47 UTC, kevinbarabash commented
This is ready for review again.

2019-01-18 16:57 UTC, jeresig approved these changes
Awesome - thank you for the verification, I appreciate it!

2019-01-18 17:00 UTC, merged